name: marquee_widget
description: "This is a Flutter package that can enable you turn any Widget into a Marquee."
version: 0.0.1
homepage: https://github.com/mayupandey/marquee_widget

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

